create table if not exists items (
  id bigserial primary key,
  item_key text not null unique,
  name text not null,
  category text not null,
  item_type text not null,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists quiz_events (
  id bigserial primary key,
  session_id text not null,
  quiz_category text not null,
  left_item_key text references items(item_key) on delete set null,
  right_item_key text references items(item_key) on delete set null,
  chosen_item_key text not null references items(item_key) on delete cascade,
  is_correct boolean not null,
  response_ms integer,
  created_at timestamptz not null default now()
);

create table if not exists awards_events (
  id bigserial primary key,
  session_id text not null,
  awards_category text not null,
  round_name text not null,
  group_name text,
  matchup_id text,
  left_item_key text references items(item_key) on delete set null,
  right_item_key text references items(item_key) on delete set null,
  chosen_item_key text not null references items(item_key) on delete cascade,
  created_at timestamptz not null default now()
);

-- One row represents one confirmed board-game PLAY action. The session ID is
-- anonymous and generated by the client; no account or character data is kept.
create table if not exists boardgame_play_events (
  id bigserial primary key,
  event_id text not null unique,
  session_id text not null,
  game_mode text not null,
  game_variant text,
  device_type text not null default 'unknown'
    check (device_type in ('desktop', 'mobile', 'tablet', 'unknown')),
  created_at timestamptz not null default now(),
  check (char_length(event_id) between 8 and 128),
  check (char_length(session_id) between 8 and 128),
  check (char_length(game_mode) between 1 and 64),
  check (game_variant is null or char_length(game_variant) between 1 and 64)
);

create index if not exists idx_items_category on items(category);
create index if not exists idx_quiz_events_category on quiz_events(quiz_category);
create index if not exists idx_quiz_events_chosen_item_key on quiz_events(chosen_item_key);
create index if not exists idx_quiz_events_created_at on quiz_events(created_at);
create index if not exists idx_awards_events_category on awards_events(awards_category);
create index if not exists idx_awards_events_round_name on awards_events(round_name);
create index if not exists idx_awards_events_chosen_item_key on awards_events(chosen_item_key);
create index if not exists idx_awards_events_created_at on awards_events(created_at);
create index if not exists idx_boardgame_play_events_mode_created_at
  on boardgame_play_events(game_mode, created_at desc);
create index if not exists idx_boardgame_play_events_session_created_at
  on boardgame_play_events(session_id, created_at desc);
create index if not exists idx_boardgame_play_events_created_at
  on boardgame_play_events(created_at desc);
